name: Translation Request
description: Request to add a new language to this extension, the user is required to give the translation.
title: "Add [LANGUAGE] translation"
labels: ["enhancement"]
assignees:
  - Tommimon
body:
  - type: markdown
    attributes:
      value: "### Language Data"
  - type: markdown
    attributes:
      value: "This section is relative to the language you are asking to add support for"
  - type: input
    id: language_name
    attributes:
      label: Language Name
      placeholder: ex. Italian
    validations:
      required: true
  - type: input
    id: language_code
    attributes:
      label: Language Code
      placeholder: ex. it
    validations:
      required: true
  - type: input
    id: plural_forms
    attributes:
      label: Plural Forms
    validations:
      required: false
  - type: markdown
    attributes:
      value: "### Translator Data"
  - type: markdown
    attributes:
      value: "Fill this section with your personal details"
  - type: input
    id: translator_username
    attributes:
      label: Username
    validations:
      required: true
  - type: input
    id: translator_email
    attributes:
      label: Email
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Translation"
  - type: input
    id: add_to_desktop
    attributes:
      label: Add to Desktop
      description: Give your translation for the expression `Add to Desktop`
    validations:
      required: true
  - type: markdown
    attributes:
      value: "Thanks for taking the time to fill out this translation request!"
